# Generated by Django 3.2.7 on 2024-11-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='jewelry_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelries', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('jewelry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.jewelry')),
                ('material', models.CharField(max_length=50)),
                ('clasp_type', models.CharField(max_length=50)),
            ],
            bases=('shop.jewelry',),
        ),
        migrations.CreateModel(
            name='Earring',
            fields=[
                ('jewelry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.jewelry')),
                ('length', models.FloatField()),
                ('style', models.CharField(max_length=50)),
            ],
            bases=('shop.jewelry',),
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('jewelry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.jewelry')),
                ('length', models.FloatField()),
                ('pendant_type', models.CharField(max_length=50)),
            ],
            bases=('shop.jewelry',),
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('jewelry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.jewelry')),
                ('size', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=50)),
            ],
            bases=('shop.jewelry',),
        ),
    ]
