# Generated by Django 3.2.7 on 2024-11-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
