# Generated by Django 3.2.7 on 2024-11-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
